// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using akbkoleso.Data;

namespace akbkoleso.Migrations.akbkolesoCatalog
{
    [DbContext(typeof(akbkolesoCatalogContext))]
    partial class akbkolesoCatalogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("akbkoleso.Models.Admin.Catalog.Catalog_tires_wheels", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Car")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diametr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gaika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pcd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tuning_diski")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tuning_shini")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zamen_diskov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zamen_shini")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zavod_diskov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zavod_shini")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Catalog_tires_wheelss");
                });

            modelBuilder.Entity("akbkoleso.Models.Admin.Catalog.Podbor_akb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Car")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diametr_klem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dlina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emkost_do")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emkost_ot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mochnost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Polarnost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shirina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tok_xol_prok")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Visota")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Podbor_akbs");
                });
#pragma warning restore 612, 618
        }
    }
}
